object ResBathForm: TResBathForm
  Left = 280
  Top = 169
  BorderStyle = bsDialog
  Caption = #1054#1073#1097#1072#1103' '#1041#1072#1085#1103', '#1087#1088#1077#1076#1074#1072#1088#1080#1090#1077#1083#1100#1085#1072#1103' '#1079#1072#1087#1080#1089#1100
  ClientHeight = 678
  ClientWidth = 802
  Color = clBtnFace
  Font.Charset = RUSSIAN_CHARSET
  Font.Color = clWindowText
  Font.Height = -13
  Font.Name = 'Verdana'
  Font.Style = []
  OldCreateOrder = False
  Position = poDesktopCenter
  OnDestroy = FormDestroy
  OnShow = FormShow
  PixelsPerInch = 96
  TextHeight = 16
  object Panel1: TPanel
    Left = 0
    Top = 0
    Width = 802
    Height = 654
    Align = alTop
    TabOrder = 0
    object pcResBath: TPageControl
      Left = 1
      Top = 30
      Width = 800
      Height = 623
      ActivePage = TabSheet1
      Align = alClient
      Font.Charset = RUSSIAN_CHARSET
      Font.Color = clWindowText
      Font.Height = -13
      Font.Name = 'Verdana'
      Font.Style = [fsBold]
      ParentFont = False
      TabIndex = 0
      TabOrder = 0
      object TabSheet1: TTabSheet
        Caption = #1052
        Font.Charset = RUSSIAN_CHARSET
        Font.Color = clWindowText
        Font.Height = -13
        Font.Name = 'Verdana'
        Font.Style = [fsBold]
        ParentFont = False
        OnShow = TabSheet1Show
        object sgM3: TStringGrid
          Tag = 2
          Left = 530
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 2
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
        object sgM2: TStringGrid
          Tag = 1
          Left = 265
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 1
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
        object sgM1: TStringGrid
          Left = 0
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 0
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
        object edInput: TMaskEdit
          Left = 384
          Top = 32
          Width = 120
          Height = 18
          BevelKind = bkFlat
          BorderStyle = bsNone
          EditMask = '!90:00;1;_'
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = []
          MaxLength = 5
          ParentFont = False
          TabOrder = 3
          Text = '  :  '
          Visible = False
          OnExit = edInputExit
        end
      end
      object TabSheet2: TTabSheet
        Caption = #1046
        ImageIndex = 1
        OnShow = TabSheet2Show
        object sgF3: TStringGrid
          Left = 530
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 0
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
        object sgF2: TStringGrid
          Left = 265
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 1
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
        object sgF1: TStringGrid
          Left = 0
          Top = 0
          Width = 265
          Height = 592
          TabStop = False
          Align = alLeft
          ColCount = 3
          DefaultRowHeight = 18
          FixedCols = 0
          RowCount = 31
          Options = [goFixedVertLine, goFixedHorzLine, goVertLine, goHorzLine, goColSizing]
          ScrollBars = ssVertical
          TabOrder = 2
          OnDblClick = sgM1DblClick
          OnDrawCell = sgM1DrawCell
          OnKeyDown = sgM1KeyDown
          OnSelectCell = sgM1SelectCell
        end
      end
    end
    object Panel3: TPanel
      Left = 1
      Top = 1
      Width = 800
      Height = 29
      Align = alTop
      TabOrder = 1
      object Panel14: TPanel
        Left = 1
        Top = 1
        Width = 798
        Height = 26
        Align = alTop
        BevelInner = bvLowered
        BevelOuter = bvNone
        TabOrder = 0
        object sbFitMo: TSpeedButton
          Tag = 1
          Left = 2
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Down = True
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clRed
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitTu: TSpeedButton
          Tag = 2
          Left = 88
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitWe: TSpeedButton
          Tag = 3
          Left = 174
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitTh: TSpeedButton
          Tag = 4
          Left = 260
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitFr: TSpeedButton
          Tag = 5
          Left = 346
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clWindowText
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitSa: TSpeedButton
          Tag = 6
          Left = 432
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitSu: TSpeedButton
          Tag = 7
          Left = 518
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
        object sbFitAlt: TSpeedButton
          Tag = 8
          Left = 603
          Top = 2
          Width = 85
          Height = 24
          GroupIndex = 1
          Font.Charset = RUSSIAN_CHARSET
          Font.Color = clBlack
          Font.Height = -13
          Font.Name = 'Verdana'
          Font.Style = [fsBold]
          ParentFont = False
          OnClick = sbFitMoClick
        end
      end
    end
    object Button1: TButton
      Left = 251
      Top = 32
      Width = 90
      Height = 25
      Caption = #1054#1089#1074#1086#1073#1086#1076#1080#1090#1100
      TabOrder = 2
      OnClick = Button1Click
    end
    object Button2: TButton
      Left = 175
      Top = 32
      Width = 75
      Height = 25
      Caption = #1047#1072#1085#1103#1090#1100
      TabOrder = 3
      OnClick = Button2Click
    end
    object Button3: TButton
      Left = 535
      Top = 32
      Width = 100
      Height = 25
      Caption = #1040#1085#1085#1091#1083#1080#1088#1086#1074#1072#1090#1100
      TabOrder = 4
      OnClick = Button3Click
    end
    object Button4: TButton
      Left = 369
      Top = 32
      Width = 75
      Height = 25
      Caption = #1050' '#1050#1083#1080#1077#1085#1090#1091
      TabOrder = 5
      OnClick = Button4Click
    end
  end
  object Panel2: TPanel
    Left = 0
    Top = 654
    Width = 802
    Height = 24
    Align = alClient
    TabOrder = 1
  end
end
